# Generated by Django 2.0 on 2017-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nav')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='url')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name_plural': 'nav',
                'ordering': ['-create_time'],
                'verbose_name': 'nav',
            },
        ),
    ]
