# Generated by Django 2.0 on 2017-12-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'category',
                'ordering': ['rank', '-create_time'],
                'verbose_name_plural': 'category',
            },
        ),
    ]
