# Generated by Django 2.0 on 2017-12-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('en_title', models.CharField(max_length=100)),
                ('img', models.CharField(default='/static/img/article/default.jpg', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='help text', max_length=200, null=True, verbose_name='tags')),
                ('summary', models.TextField(verbose_name='summary')),
                ('content', models.TextField(verbose_name='content')),
                ('view_times', models.IntegerField(default=0)),
                ('zan_times', models.IntegerField(default=0)),
                ('is_top', models.BooleanField(default=False, verbose_name='top')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='status')),
                ('pub_time', models.DateTimeField(default=False, verbose_name='published')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name_plural': 'post',
                'ordering': ['rank', '-is_top', '-pub_time', '-create_time'],
                'verbose_name': 'post',
            },
        ),
    ]
