# Generated by Django 2.0 on 2017-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('summary', models.TextField(verbose_name='summary')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('post', models.ManyToManyField(to='nblog.Post', verbose_name='post')),
            ],
            options={
                'verbose_name_plural': '专栏',
                'ordering': ['-create_time'],
                'verbose_name': '专栏',
            },
        ),
    ]
