# Generated by Django 2.0 on 2017-12-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0004_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('img', models.CharField(default='/static/img/carousel/default.jpg', max_length=200, verbose_name='image')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name_plural': 'carousel',
                'verbose_name': 'carousel',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='news')),
                ('summary', models.TextField(verbose_name='summary')),
                ('news_from', models.IntegerField(choices=[(0, 'oschina'), (1, 'chiphell'), (2, 'freebuf'), (3, 'cnBeta')], default=0, verbose_name='news_form')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('pub_time', models.DateTimeField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name_plural': 'news',
                'verbose_name': 'news',
                'ordering': ['-title'],
            },
        ),
    ]
